# Generated by Django 4.2.4 on 2023-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ha', models.FloatField()),
                ('PPAHa', models.FloatField(blank=True, null=True)),
                ('PCHa', models.FloatField(blank=True, null=True)),
                ('PLHa', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
